services:
  - type: web
    name: db-app
    runtime: node
    repo: https://github.com/Ohenheim/ESGI.Render.4A.Static
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bp-db
          property: connectionString

databases:
  - name: bp-db
    plan: free
    region: frankfurt
